CREATE TABLE USUARIOS (
    ID_USU VARCHAR(10) PRIMARY KEY,
    NOM_USU VARCHAR(30) NOT NULL,
    APE_USU VARCHAR(30) NOT NULL,
    CON_USU VARCHAR(255) NOT NULL
    
);

CREATE TABLE EVENTOS (
    ID_USU_PER VARCHAR(10),
    FEC_EVE DATE NOT NULL,
    HOR_EVE TIME NOT NULL,
    TIT_EVE VARCHAR(100) NOT NULL,
    DES_EVE VARCHAR(255),
    FOREIGN KEY (ID_USU_PER) REFERENCES USUARIOS(ID_USU)
);